name: KiCad ERC Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  erc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run ERC
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          schematic_file_name: ./Klask_PCB.kicad_sch
          run_erc: true

          pcb_file_name: ./Klask_PCB.kicad_pcb
          run_drc: true
