name: Export KiCad PDFs

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  export-pdfs:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:10.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Export all outputs
        run: just export

      - name: Upload schematic
        uses: actions/upload-artifact@v7
        with:
          path: ./output/SCH.pdf
          archive: false

      - name: Upload PCB PDFs
        uses: actions/upload-artifact@v7
        with:
          name: PCB-PDFs
          path: |
            ./output/PCB_F.pdf
            ./output/PCB_B.pdf

      - name: Upload gerbers and drill files
        uses: actions/upload-artifact@v7
        with:
          name: Gerbers
          path: ./output/gerbers

      - name: Upload image renders
        uses: actions/upload-artifact@v7
        with:
          name: PCB-Images
          path: ./output/pcb*.png
