name: Export KiCad PDFs

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  export-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Export schematic, gerbers, and front image
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          schematic_file_name: ./Klask_PCB.kicad_sch
          run_erc: false
          schematic_output_pdf: true

          pcb_file_name: ./Klask_PCB.kicad_pcb
          run_drc: false
          pcb_output_gerbers_and_drill: true
          pcb_output_image: true
          pcb_output_image_side: front
          pcb_output_image_file_name: pcb_front.png

      - name: Export back image
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          pcb_file_name: ./Klask_PCB.kicad_pcb
          run_drc: false
          pcb_output_image: true
          pcb_output_image_side: back
          pcb_output_image_file_name: pcb_back.png

      - name: Upload schematic
        uses: actions/upload-artifact@v7
        with:
          path: ./schematic.pdf
          archive: false

      - name: Upload gerbers and drill file
        uses: actions/upload-artifact@v7
        with:
          name: Gerbers
          path: ./gerbers

      - name: Upload image renders
        uses: actions/upload-artifact@v7
        with:
          name: PCB-Images
          path: ./pcb*.png
